# coding: utf-8

"""
    Blockstore API

    REST API for Open edX Blockstore  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ApiV1IndexBlocksSummary(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'image': 'str',
        'description': 'str',
        'title': 'str'
    }

    attribute_map = {
        'image': 'image',
        'description': 'description',
        'title': 'title'
    }

    def __init__(self, image=None, description=None, title=None):  # noqa: E501
        """ApiV1IndexBlocksSummary - a model defined in OpenAPI"""  # noqa: E501

        self._image = None
        self._description = None
        self._title = None
        self.discriminator = None

        self.image = image
        self.description = description
        self.title = title

    @property
    def image(self):
        """Gets the image of this ApiV1IndexBlocksSummary.  # noqa: E501


        :return: The image of this ApiV1IndexBlocksSummary.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this ApiV1IndexBlocksSummary.


        :param image: The image of this ApiV1IndexBlocksSummary.  # noqa: E501
        :type: str
        """
        if image is not None and len(image) < 1:
            raise ValueError("Invalid value for `image`, length must be greater than or equal to `1`")  # noqa: E501

        self._image = image

    @property
    def description(self):
        """Gets the description of this ApiV1IndexBlocksSummary.  # noqa: E501


        :return: The description of this ApiV1IndexBlocksSummary.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ApiV1IndexBlocksSummary.


        :param description: The description of this ApiV1IndexBlocksSummary.  # noqa: E501
        :type: str
        """
        if description is not None and len(description) < 1:
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def title(self):
        """Gets the title of this ApiV1IndexBlocksSummary.  # noqa: E501


        :return: The title of this ApiV1IndexBlocksSummary.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ApiV1IndexBlocksSummary.


        :param title: The title of this ApiV1IndexBlocksSummary.  # noqa: E501
        :type: str
        """
        if title is not None and len(title) < 1:
            raise ValueError("Invalid value for `title`, length must be greater than or equal to `1`")  # noqa: E501

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiV1IndexBlocksSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
