# coding: utf-8

"""
    Blockstore API

    REST API for Open edX Blockstore  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Taxonomy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'owner': 'Entity'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'owner': 'owner'
    }

    def __init__(self, id=None, name=None, owner=None):  # noqa: E501
        """Taxonomy - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._name = None
        self._owner = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if owner is not None:
            self.owner = owner

    @property
    def id(self):
        """Gets the id of this Taxonomy.  # noqa: E501


        :return: The id of this Taxonomy.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Taxonomy.


        :param id: The id of this Taxonomy.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Taxonomy.  # noqa: E501


        :return: The name of this Taxonomy.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Taxonomy.


        :param name: The name of this Taxonomy.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 180:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `180`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def owner(self):
        """Gets the owner of this Taxonomy.  # noqa: E501


        :return: The owner of this Taxonomy.  # noqa: E501
        :rtype: Entity
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Taxonomy.


        :param owner: The owner of this Taxonomy.  # noqa: E501
        :type: Entity
        """

        self._owner = owner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Taxonomy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
